# Generated by Django 4.2.3 on 2023-09-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=100)),
                ('Block', models.BooleanField(default=False)),
                ('Delete', models.BooleanField(default=False)),
            ],
        ),
    ]
