# Generated by Django 4.2.3 on 2023-09-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customur',
            name='Image',
            field=models.FileField(default='static/img/avatars/profile_avter.webp', upload_to='media/profile/images'),
        ),
    ]
