# Generated by Django 4.2.3 on 2023-09-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_file', '0002_customur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customur',
            name='Adress',
            field=models.CharField(default='not available', max_length=300),
        ),
    ]
