# Generated by Django 3.2.3 on 2023-10-01 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_file', '0003_customur_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
                ('Image', models.FileField(upload_to='midea/ProductImages/')),
                ('Price', models.ImageField(default=0, upload_to='')),
                ('Short_Discreption', models.TextField()),
                ('Discreption', models.TextField()),
                ('Date', models.DateField(default=datetime.datetime(2023, 10, 1, 14, 38, 20, 886400))),
            ],
        ),
    ]
