# Generated by Django 3.2.3 on 2023-10-01 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_file', '0004_productprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='Date',
            field=models.DateField(default=datetime.datetime(2023, 10, 1, 15, 39, 57, 229699)),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
