# Generated by Django 3.2.3 on 2023-10-01 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_file', '0006_auto_20231001_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='Date',
            field=models.DateField(default=datetime.datetime(2023, 10, 1, 15, 47, 34, 194276)),
        ),
    ]
